version: '3'
services:
  api:
    container_name: api
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEMO=y
    ports:
      - "8000:8000"
