version: "3"
services:
  d4database:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ${D4DB_VOLUME}:/var/lib/mysql
      - ${DATA_VOLUME}:${DATA_VOLUME}
    healthcheck:
      test: "/usr/bin/mysql --user=${D4DB_USER_NAME} --password=${D4DB_USER_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 5s
      retries: 10
  chanjo2-demo:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MYSQL_ROOT_PASSWORD=${D4DB_USER_PASSWORD}
    depends_on:
      d4database:
        condition: service_healthy
      
