FROM clinicalgenomics/pyd4

LABEL base_image="clinicalgenomics/pyd4"
LABEL about.home="https://github.com/Clinical-Genomics/chanjo2"

WORKDIR /home/worker/app
COPY . /home/worker/app

# Install poetry
RUN apt-get update 
RUN apt-get install -y default-libmysqlclient-dev
RUN pip install -r requirements.txt
RUN pip install .



# switch to gunicorn
CMD gunicorn\
    --config gunicorn.conf.py \
    chanjo2.main:app
