version: '3'
services:
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: Dockerfile-db # MariaDB with an init.sql file to initialize the database
    restart: 'always'
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
      - MYSQL_HOST_PORT=${MYSQL_HOST_PORT}
      - MARIADB_RANDOM_ROOT_PASSWORD=T
    healthcheck: # Wait for the service to be ready before accepting incoming connections
      test: "mariadb --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute \"SHOW DATABASES;\""
      timeout: 10s
      retries: 20
    volumes:
      - ${HOST_DATA_VOLUME}:${CONTAINER_DATA_VOLUME}
    networks:
      - chanjo-net
    ports:
      - "${MYSQL_HOST_PORT}:3306"

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./template.env:/home/worker/app/.env
      - ${HOST_DATA_VOLUME}:${CONTAINER_DATA_VOLUME}
    networks:
      - chanjo-net
    ports:
      - "${CHANJO_HOST_PORT}:8000"

networks:
  chanjo-net:
    driver: bridge
