version: '3'
# usage:
# (sudo) docker-compose up -d
# (sudo) docker-compose down
services:
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: 'always'
    environment:
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_DATABASE_NAME=${DB_NAME}
    healthcheck: # Wait for the service to be ready before accepting incoming connections
      test: "mysql --user=${DB_USER_NAME} --password=${DB_USER_PASSWORD} --execute \"SHOW DATABASES;\""
      timeout: 10s
      retries: 20
    volumes:
      - ${HOST_DATA_VOLUME}:${CONTAINER_DATA_VOLUME}
    networks:
      - chanjo-net
    ports:
      - "${MYSQL_HOST_PORT}:3306"

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_DATABASE_NAME=${DB_NAME}
      - MYSQL_HOST_NAME=${MYSQL_HOST_NAME} # This is set to mariadb (the db service) to work in docker-compose
      - MYSQL_PORT=${MYSQL_PORT} # This will be empty to work in docker-compose
    depends_on:
      mariadb:
        condition: service_healthy # DB_URI=root:testpw@mariadb/testdb
    volumes:
      - ${HOST_DATA_VOLUME}:${CONTAINER_DATA_VOLUME}
    networks:
      - chanjo-net
    ports:
      - "${CHANJO_HOST_PORT}:8000"

networks:
  chanjo-net:
    driver: bridge
