version: '3'
services:
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: Dockerfile-db # MariaDB with an init.sql file to initialize the database
    restart: 'always'
    environment:
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_DATABASE_NAME=${DB_NAME}
    healthcheck: # Wait for the service to be ready before accepting incoming connections
      test: "mysql --user=${DB_USER_NAME} --password=${DB_USER_PASSWORD} --execute \"SHOW DATABASES;\""
      timeout: 10s
      retries: 20
    volumes:
      - ${HOST_DATA_VOLUME}:${CONTAINER_DATA_VOLUME}
    networks:
      - chanjo-net
    ports:
      - "${MYSQL_HOST_PORT}:3306"

  api:
    container_name: api
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_DATABASE_NAME=${DB_NAME}
      - MYSQL_HOST_NAME=${MYSQL_HOST_NAME}
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ${HOST_DATA_VOLUME}:${CONTAINER_DATA_VOLUME}
    networks:
      - chanjo-net
    ports:
      - "${CHANJO_HOST_PORT}:8000"

networks:
  chanjo-net:
    driver: bridge
