version: "3"
services:
  d4database:
    build:
      context: . 
      dockerfile: ./Dockerfile-db
    environment:
      - MYSQL_DATABASE_NAME=${D4DB_NAME}
      - MYSQL_ROOT_PASSWORD=${D4DB_USER_PASSWORD}
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
    volumes:
      - ${DATA_VOLUME}:${DATA_VOLUME}
    healthcheck:
      test: "/usr/bin/mysql --user=${D4DB_USER_NAME} --password=${D4DB_USER_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 5s
      retries: 10
  chanjo2-demo:
    build:
      context: .  
      dockerfile: ./Dockerfile-api
    ports:
      - "${CHANJO_HOST_PORT}:${CHANJO_CONTAINER_PORT}"
    environment:
      - MYSQL_DATABASE_NAME=${D4DB_NAME}
      - MYSQL_HOST_NAME=d4database
      - MYSQL_ROOT_PASSWORD=${D4DB_USER_PASSWORD}
      - MYSQL_PORT=${MYSQL_CONTAINER_PORT}
    depends_on:
      d4database:
        condition: service_healthy
      
