site_name: Chanjo2
site_url: https://clinical-genomics.github.io/chanjo2
repo_url: https://github.com/Clinical-Genomics/chanjo2/

theme: readthedocs

nav:
    - Index: "index.md"
    - Deployment:
      - Deployment using Docker: "deployment/docker-deployment.md"
      - Installation on a virtual environment: "deployment/installation.md"
    - Usage:
        - Loading and displaying genes, transcripts and exons: "usage/loading-intervals.md"
        - Interval queries: "usage/interval-queries.md"
        - Cases and samples: "usage/loading-samples.md"
        - Coverage:
            - Simple coverage queries: "usage/quick-coverage.md"
            - Coverage and coverage completeness queries on sample data: "usage/sample-coverage.md"

