name: tests & coverage

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11' ]
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry export -f requirements.txt > requirements.txt
          python -m pip install -r requirements.txt
          poetry install

      - name: Print python versions
        run: |
          poetry run python -V

      - name: Test with pytest
        run:
          poetry run pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          files: ./coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
