name: "Vulture - Find unused code"
on:
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    name: vulture
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Find changed Python files
        id: files
        uses: masesgroup/retrieve-changed-files@v2
        with:
          format: 'py'

      - name: Scavenge
        uses: anaynayak/python-vulture-action@v1.0
        id: vulture
        with:
          vulture-args: --min-confidence 80 --ignore-names kwargs cls ${{steps.files.outputs.all}}
        continue-on-error: true
