name: "Vulture - Find unused code"
on:
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    name: vulture
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            src
            tests

      - name: Scavenge
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: anaynayak/python-vulture-action@v1.0
        id: vulture
        with:
          vulture-args: --min-confidence 80 ${{steps.changed-files.outputs.all_changed_files}}
        continue-on-error: true
